spring.application.name=uber

spring.datasource.url=jdbc:postgresql://localhost:54321/uber
spring.datasource.username=user
spring.datasource.password=pass
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=VERY_SECRET_SECRET
jwt.expiration-ms=86400000
